#The first line is used for comment
!setname 0x2ea Zenet
!setname 0x2ec Fenditura dei Tre Regni
!setname 0x2ed Rilancio Lunare
!setname 0x2ee Carta Drago
!setname 0x2ef Divinità del Sole
!setname 0x2f0 Drago Alato di Ra
