#The first line is used for comment
!setname 0x1cf R.B.
!setname 0x1dd GMX
!setname 0x2e2 White Knight
!setname 0x2e3 Daedalus
!setname 0x2e4 Ashtra
!setname 0x2e5 Angelechgy
!setname 0x2e6 Ars Magna
!setname 0x2e7 Diactorus
!setname 0x2e8 Medius
!setname 0x2e9 Masquerade
!setname 0x2ea Sennet
!setname 0x2eb Dominators
!setname 0x2ec Trirealm Rift
!setname 0x2ed Raise Moon
!setname 0x2ee Dragon Card
!setname 0x2ef Sun God
!setname 0x2f0 The Winged Dragon of Ra
!setname 0x31c6 Dominus
!counter 0x76 Counter (Reversal Box)
!counter 0x77 Crown Counter
!counter 0x78 Myriad Counter
