#The first line is used for comment
!counter 0x76 Counter（Reversal Box）
!counter 0x77 Crown Counter
!setname 0x2e2 White Night
!setname 0x2e3 Levia-Dragon - Daedalus
!setname 0x2e4 Gonki
!setname 0x2e5 Gravekeeper's Visionary
