#The first line is used for comment
!counter 0x76 Compteur (Boîte du Renversement)
!counter 0x77 Compteur Couronne
!counter 0x78 Compteur Myriade
!setname 0x1cf R.B.
!setname 0x1dd GMX
!setname 0x2e2 Chevalier Blanc
!setname 0x2e3 Dédale
!setname 0x2e4 Asutra
!setname 0x2e5 Angetélité
!setname 0x2e6 Ars Magna
!setname 0x2e7 Diactorus
!setname 0x2e8 Medius
!setname 0x2e9 Mascarade
!setname 0x2ea Sennet
