#The first line is used for comment
!setname 0x2ea Sennet
!setname 0x2ec Xénovahisseur△
!setname 0x2ed Lune Relancée
!setname 0x2ee Carte du Dragon
!setname 0x2ef Dieu du Soleil
!setname 0x2f0 Le Dragon Ailé de Râ
