#The first line is used for comment
!counter 0x76 Umkehrbox-Zählmarke
!counter 0x77 Kronen-Zählmarke
!counter 0x78 Myriad Counter
!setname 0x1cf
!setname 0x1dd
!setname 0x2e2 Weißer Ritter
!setname 0x2e3 Daedalus
!setname 0x2e4 Ashtra
!setname 0x2e5 Engelechy
!setname 0x2e6
!setname 0x2e7
!setname 0x2e8
!setname 0x2e9
!setname 0x2ea
