#The first line is used for comment
!counter 0x76 Umkehrbox-Zählmarke
!counter 0x77 Kronen-Zählmarke
!counter 0x78 Myriaden-Zählmarke
!setname 0x1cf R.B.
!setname 0x1dd GMX
!setname 0x2e2 Weißer Ritter
!setname 0x2e3 Daedalus
!setname 0x2e4 Ashtra
!setname 0x2e5 Engelechy
!setname 0x2e6 Ars Magna
!setname 0x2e7 Diactorus
!setname 0x2e8 Medius
!setname 0x2e9 Maskerade
!setname 0x2ea Sennet
