#The first line is used for comment
!counter 0x75 VIP-Zählmarken
!counter 0x76
!setname 0x2df Blitzclique
!setname 0x2e0 Theorealisier
!setname 0x2e1 Aleister
!setname 0x2e2 Weißer Ritter
!setname 0x1144 Heiligen/s Ungeheuer
