#The first line is used for comment
!counter 0x75 Marcador VIP
!counter 0x76
!setname 0x2df Blitzclique
!setname 0x2e0 Teorizar
!setname 0x2e1 Aleister
!setname 0x2e2 Cavaleiro Branco
!setname 0x1144 Besta Sagrada
