#The first line is used for comment
!counter 0x79 邪心教義
!setname 0x2ea セネト
!setname 0x2ec 異解△
!setname 0x2ed レイズ・ムーン
!setname 0x2ee 魔の龍札
!setname 0x2ef 太陽神
!setname 0x2f0 ラーの翼神竜
!setname 0x2f1 リインゼルム
!setname 0x2f2 白鴉