#The first line is used for comment
!setname 0x31c6 Dominus
!setname 0x2ea Sennet
!setname 0x2eb Dominadores
!setname 0x2ec Xenovader△
!setname 0x2ed Rise Moon
!setname 0x2ee Carta Dragón
!setname 0x2ef Dios del Sol
!setname 0x2f0 El Dragón Alado de Ra
