#The first line is used for comment
!counter 0x76 Contador (Caja de Reversión)
!counter 0x77 Contador de Corona
!counter 0x78 Contador de Miríada
!setname 0x1cf R.B.
!setname 0x1dd GMX
!setname 0x2e2 Noche Blanca
!setname 0x2e3 Dédalo
!setname 0x2e4 Asutra
!setname 0x2e5 Angelechy
!setname 0x2e6 Ars Magna
!setname 0x2e7 Diactorus
!setname 0x2e8 Medius
!setname 0x2e9 Mascarada
!setname 0x2ea Sennet
