#The first line is used for comment
!setname 0x2ea Zenet
!setname 0x2ec Fisura de los Tres Reinos
!setname 0x2ed Raise Moon
!setname 0x2ee Carta Dragón
!setname 0x2ef Dios Solar
!setname 0x2f0 El Dragón Alado de Ra
