#The first line is used for comment
!counter 0x75 ＶＩＰ Ｃｏｕｎｔｅｒ
!counter 0x76 カウンター (大逆転BOX)
!setname 0x2df Ｂｌｉｔｚｃｌｉｑｕｅ
!setname 0x2e0 テオリアライズ
!setname 0x2e1 アレイスター
!setname 0x2e2 白騎士団の
!setname 0x1144 三幻魔
