#The first line is used for comment
!counter 0x76 カウンター （大逆転ＢＯＸ）
!counter 0x77 冠カウンター
!counter 0x78 万倍カウンター
!setname 0x1cf Ｒ．Ｂ．
!setname 0x1dd ＧＭＸ
!setname 0x2e2 白騎士団の
!setname 0x2e3 ダイダロス
!setname 0x2e4 アシュトラ
!setname 0x2e5 Ａｎｇｅｌｅｃｈｙ
!setname 0x2e6 アルス＝マグナ
!setname 0x2e7 ディアクトロス
!setname 0x2e8 メディウス
!setname 0x2e9 仮面魔踏士
!setname 0x2ea セネト
