#The first line is used for comment
!setname 0x31c6 Dominus
!setname 0x2ea Sennet
!setname 0x2eb Dominators
!setname 0x2ec Trirealm Rift
!setname 0x2ed Raise Moon
!setname 0x2ee Dragon Card
!setname 0x2ef Sun God
!setname 0x2f0 The Winged Dragon of Ra
