#The first line is used for comment
!counter 0x76 Marcador (Carixa da Reversão)
!counter 0x77 Marcador de Coroa
!counter 0x78 Marcador de Miríade
!setname 0x1cf R.B.
!setname 0x1dd GMX
!setname 0x2e2 Cavaleiro Branco
!setname 0x2e3 Daedalus
!setname 0x2e4 Asutra
!setname 0x2e5 Angelechgy
!setname 0x2e6 Ars Magna
!setname 0x2e7 Diactorus
!setname 0x2e8 Medius
!setname 0x2e9 Mascarado
!setname 0x2ea Sennet
