#The first line is used for comment
!counter 0x75 Compteur VIP
!counter 0x76 Compteur (Boîte du Renversement)
!setname 0x2df Blitzclique
!setname 0x2e0 Théoréalisation
!setname 0x2e1 Aleister
!setname 0x2e2 Chevalier Blanc
!setname 0x1144 Bêtes Sacrées
